is_training = true
root_path = "./dataset/ETT/"
data_path = "ETTh2.csv"
model_id_base = "ETTh2"
model = "PathFormer"
data = "ETTh2"
features = "M"
seq_len = 96
num_nodes = 7
layer_nums = 3
batch_norm = 0
residual_connection = 0
train_epochs = 30
patience = 10
lradj = "TST"
itr = 1
learning_rate = 0.0005
log_dir = "./logs/LongForecasting"


[[runs]]
pred_len = 96
patch_size_list = [16, 12, 8, 32, 12, 8, 6, 4, 8, 6, 4, 2]
k = 2
d_model = 4
batch_size = 512

[[runs]]
pred_len = 192
patch_size_list = [16, 12, 8, 32, 12, 8, 6, 4, 8, 6, 4, 2]
k = 2
d_model = 8
batch_size = 512


[[runs]]
pred_len = 336
patch_size_list = [16, 12, 8, 32, 12, 8, 6, 4, 8, 6, 4, 2]
k = 2
d_model = 4
batch_size = 512

[[runs]]
pred_len = 720
patch_size_list = [16, 12, 8, 32, 12, 8, 6, 32, 8, 6, 16, 12]
k = 3
d_model = 16
batch_size = 512
