is_training = true          
root_path = "./dataset/ETT/" 
data_path = "ETTm2.csv"      
model_id_base = "ETTm2"     
model = "PathFormer"        
data = "ETTm2"             
features = "M"
seq_len = 96                
patch_size_list = [16, 12, 8, 32, 12, 8, 6, 32, 8, 6, 16, 12] 
num_nodes = 7               
layer_nums = 3              
k = 2                       
d_model = 16                
d_ff = 64                   
train_epochs = 30
patience = 10
lradj = "TST"
itr = 1
batch_size = 512           
learning_rate = 0.001       


log_dir = "./logs/LongForecasting"



[[runs]]
pred_len = 96

[[runs]]
pred_len = 192

[[runs]]
pred_len = 336

[[runs]]
pred_len = 720

