is_training = true          
root_path = "./dataset/ETT/" 
data_path = "ETTm1.csv"      
model_id_base = "ETTm1"     
model = "PathFormer"        
data = "ETTm1"              
features = "M"
seq_len = 96                
patch_size_list = [16, 12, 8, 4, 12, 8, 6, 4, 8, 6, 2, 12] 
batch_norm = 0              
residual_connection = 1     
num_nodes = 7
layer_nums = 3
k = 3                       
d_model = 8                 
d_ff = 64                  
train_epochs = 30
patience = 10
lradj = "TST"
itr = 1
batch_size = 512           
learning_rate = 0.0005      

log_dir = "./logs/LongForecasting"


[[runs]]
pred_len = 96

[[runs]]
pred_len = 192

[[runs]]
pred_len = 336

[[runs]]
pred_len = 720

